### ISSUE TITLE
Latest release crashes on graphene

### ISSUE THREAD

**Issue by acidvegas** [simondankelmann/Bluetooth-LE-Spam#149]
```
type: crash
osVersion: google/lynx/lynx:14/UP1A.231105.003/2023112900:user/release-keys
package: de.simon.dankelmann.bluetoothlespam:1
process: de.simon.dankelmann.bluetoothlespam
processUptime: 133 + 243 ms
installer: dev.imranr.obtainium

java.lang.RuntimeException: Unable to create service de.simon.dankelmann.bluetoothlespam.Services.AdvertisementForegroundService: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{ad7441 20433:de.simon.dankelmann.bluetoothlespam/u0a158} targetSDK=34
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4681)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2271)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{ad7441 20433:de.simon.dankelmann.bluetoothlespam/u0a158} targetSDK=34
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4890)
	at android.os.Parcel.readParcelable(Parcel.java:4872)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6776)
	at android.app.Service.startForeground(Service.java:775)
	at de.simon.dankelmann.bluetoothlespam.Services.AdvertisementForegroundService.onCreate(AdvertisementForegroundService.kt:57)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4668)
	... 11 more

```

Crashes on boot and when trying to start an attack.

**Comment by simondankelmann** [comment]
Please try again, I changed the APK. Thx for the log :)

**Comment by acidvegas** [comment]
All good now! Thanks for the speedy fix bredda.
